---
title: "Class 13 Activity: Mutating Joins"
author: "Pete Benbow"
date: "Oct 8, 2024"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(nycflights13)
```

## Cartoon Characters

Add a column to the toon_char data frame that contains a movie the character was in, and another column with the year the movie was made

Hint: one of the data frames needs to be tidied before it is ready to join to the other one
```{r}
toon_char <- read_excel("toons_v2.xlsx", sheet = "characters")
toon_movies <- read_excel("toons_v2.xlsx", sheet = "movies")


tidy_toon_movies <- toon_movies %>% 
  pivot_longer(starts_with("char"), 
               names_to=NULL, 
               values_to="character",
               values_drop_na = TRUE)

# Answer is given by this left join
(toon_char_plus <- toon_char %>%
  left_join(tidy_toon_movies,           #rows uniquely identified in toon_char
            by=c("name"="character")))  #column names in order df's are listed

# Compare to what is created by this left join
#    * has characters not in toon_char
#    * missing some characters in toon_char 
(toon_movies_plus <- tidy_toon_movies %>%
    left_join(toon_char,
              by=c("character"="name")))

# Could get the correct answer (except columns in a different order)
#     * without the intermediate df 'tidy_toon_movies'
#     * using a right join after tidying 

toon_movies %>% 
  pivot_longer(starts_with("char"), 
               names_to=NULL, 
               values_to="character",
               values_drop_na = TRUE) %>%
  right_join(toon_char,
              by=c("character"="name"))

```


## Exercise 13.4.6 #2 
Using the data frames flights and airports, add the lat and long for the origin and destination of each flight.

```{r, echo=TRUE}
flights
airports

# Make a simpler data frame with airport name and location, so we don't pull in a bunch of stuff we don't want, and then have to get rid of it with select
airport_locations <- airports %>%
  select(faa, lat, lon)

flights %>%
  # this select is optional, just to make a simpler data frame, easier to read
  select(year:day, hour, origin, dest) %>% 
  # the first join pulls in the origin airport location (lat and lon)
  left_join(airport_locations, 
            by = c("origin" = "faa")) %>%
  # the second join pulls in the destination airport location (lat and lon)
  # the suffix makes clear variable names for each lat and lon (try it without this line to see what happens)
  left_join(airport_locations, 
            by = c("dest" = "faa"),
            suffix = c("_origin", "_dest")) 

```

